//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penjualan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pembayaran
    {
        public int id_pembayaran { get; set; }
        public int no_faktur { get; set; }
        public int id_customer { get; set; }
        public int jumlah_pembayaran { get; set; }
        public int total_bunga { get; set; }
        public System.DateTime tgl_pembayaran { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Transaksi Transaksi { get; set; }
    }
}
