//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penjualan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaksi()
        {
            this.Pembayarans = new HashSet<Pembayaran>();
        }
    
        public int no_faktur { get; set; }
        public int id_customer { get; set; }
        public System.DateTime tgl_penjualan { get; set; }
        public System.DateTime tgl_deadline { get; set; }
        public int total_biaya { get; set; }
        public int bunga { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pembayaran> Pembayarans { get; set; }
    }
}
